In [21]:
import os

for file in os.listdir():
    print(repr(file))

'.config'
'sample_data'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [25]:
from google.colab import files
uploaded = files.upload()

Saving Sample - Superstore.csv to Sample - Superstore.csv

In [26]:
import pandas as pd

filename = list(uploaded.keys())[0]
print(filename)

df = pd.read_csv(filename, encoding="latin1")
df.head()

Sample - Superstore.csv

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [27]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

df["order_date"] = pd.to_datetime(df["order_date"])
df["ship_date"] = pd.to_datetime(df["ship_date"])

df["total_sales"] = df["sales"] * df["quantity"]

df = df.dropna()

df.to_csv("cleaned_superstore.csv", index=False)

print("Cleaned data saved.")

Cleaned data saved.

In [28]:
import sqlite3

conn = sqlite3.connect("superstore.db")

df.to_sql("sales", conn, if_exists="replace", index=False)

print("Loaded into SQL database.")

Loaded into SQL database.

In [29]:
query = """
SELECT region, ROUND(SUM(total_sales),2) AS total_sales
FROM sales
GROUP BY region
ORDER BY total_sales DESC
"""

pd.read_sql(query, conn)

    region  total_sales
0     West   3595227.52
1     East   3379326.25
2  Central   2475832.94
3    South   2037675.35

In [30]:
query = """
SELECT product_name, ROUND(SUM(total_sales),2 ) AS revenue
FROM sales
GROUP BY product_name
ORDER BY revenue DESC
LIMIT 10
"""

pd.read_sql(query, conn)

                                        product_name    revenue
0              Canon imageCLASS 2200 Advanced Copier  253399.28
1   GBC Ibimaster 500 Manual ProClick Binding System  171524.89
2  Cisco TelePresence System EX90 Videoconferenci...  135830.88
3       HON 5400 Series Task Chairs for Big and Tall  124494.05
4                            Samsung Galaxy Mega 6.3  118101.19
5               Hewlett Packard LaserJet 3310 Copier  111478.14
6  Fellowes PB500 Electric Punch Plastic Comb Bin...  100662.41
7          Lexmark MX611dhe Monochrome Laser Printer   93329.45
8   3D Systems Cube Printer, 2nd Generation, Magenta   84499.35
9  Riverside Palais Royal Lawyers Bookcase, Royal...   81561.13

In [31]:
query = """
SELECT segment, ROUND(SUM(total_sales),2) AS profit
FROM sales
GROUP BY segment
ORDER BY total_sales DESC
"""

pd.read_sql(query, conn)

       segment      profit
0     Consumer  5819347.40
1  Home Office  2152607.00
2    Corporate  3516107.67

In [32]:
from google.colab import files
files.download("cleaned_superstore.csv")